# Generated by Django 5.1.6 on 2025-02-17 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_rename_massage_message_alter_room_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='Room',
            new_name='room',
        ),
    ]
