# Generated by Django 5.1.6 on 2025-02-18 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_room_participents'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='participents',
            new_name='participants',
        ),
    ]
